import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/context/AuthProvider";
import { Toaster } from "@/components/ui/toaster";



const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "GhostNote",
    description: "Generated by create next app",
    icons: {
        icon:['/fevicon.ico']
    }
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <AuthProvider>

                <body
                    className={`${geistSans.variable} ${geistMono.variable} antialiased`}
                >
                    
                    {children}
                    <Toaster></Toaster>
                </body>
            </AuthProvider>
        </html>
    );
}
